version: '3'

services:      
    nginx:    
        build: ./nginx/  
        container_name: nginx-container  
        ports:  
            - 80:80  
        links:  
            - php  

    php:    
        build: ./php/  
        container_name: php-container  
        expose:  
            - 9000  
        volumes:
            - ./www/html/pictures:/var/www/html/pictures:rw # volume mount for the pictures folder
            - ./data/data.db:/app/data/data.db:rw # volume mount for the SQLite database  