version: '3'

services:      
    nginx:    
        build: ./nginx/  
        container_name: nginx-container  
        ports:  
            - 80:80  
        links:  
            - php  

    php:    
        build: ./php/  
        container_name: php-container  
        expose:  
            - 9000  
        volumes_from:  
            - app-data
        volumes:
            - ./www/html/pictures:/var/www/html/pictures:rw  
            - ./data/data.sqlite3:/app/data/data.sqlite3:rw  

    app-data:    
        image: php:7.0-fpm  
        container_name: app-data-container  
        volumes:  
            - ./www/html/:/var/www/html/  
        command: "true"  